"""Regra 6: nada de ferramenta de IA no que fica registrado.

Cobre os três modos e, principalmente, os dois erros que tornariam a
verificação inútil: deixar passar atribuição real, e gritar em referência de
caminho legítima — monitor que dá falso positivo deixa de ser lido.
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "scripts"))
import verifica_atribuicao as va  # noqa: E402

ATRIBUICOES = [
    "Co-Authored-By: Claude Opus 5 <noreply@anthropic.com>",
    "co-authored-by: claude <x@anthropic.com>",
    "_Generated by [Claude Code](https://claude.ai/code)_",
    "🤖 Generated with Claude Code",
    "escrito com apoio da Anthropic",
    "ver claude.ai para detalhes",
]

LEGITIMOS = [
    "detalhe em `.claude/skills/conector-alupdata/SKILL.md`",
    "CLAUDE.md aponta para AGENTS.md e não duplica conteúdo",
    "Adiciona .claude/skills/ com quatro skills do projeto",
    "docs: cláusula 7ª no resumo; inclui o rateio entre coligadas",
    "fix: conserta a janela de ingestão do conector ONS",
]


@pytest.mark.parametrize("texto", ATRIBUICOES)
def test_atribuicao_e_recusada(texto: str) -> None:
    assert va.infracoes(texto), f"deveria recusar: {texto!r}"


@pytest.mark.parametrize("texto", LEGITIMOS)
def test_caminho_real_do_repositorio_nao_e_infracao(texto: str) -> None:
    """`.claude/skills/` e `CLAUDE.md` existem de verdade e são citáveis."""
    assert not va.infracoes(texto), f"falso positivo em: {texto!r}"


def test_comentario_do_git_e_ignorado() -> None:
    """Linha iniciada por # é instrução do editor, não vai para a mensagem."""
    assert not va.infracoes("fix: algo\n# Co-Authored-By: Claude <x@anthropic.com>")


def test_atribuicao_no_meio_do_texto_e_pega() -> None:
    """O rodapé real vinha depois de parágrafos legítimos, não sozinho."""
    corpo = "Bom dia.\n\nSegue o relatório.\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"
    achados = va.infracoes(corpo)
    assert len(achados) == 1
    assert "Generated by" in achados[0]


# ------------------------------------------------------------------- GitHub


def _buscador(itens: dict[str, list[dict]]):
    """Substitui a chamada ao GitHub por um retorno fixo, sem rede."""
    return lambda _repo, endpoint: itens.get(endpoint, [])


def test_github_detecta_rodape_em_comentario() -> None:
    achados = va.verificar_github(
        "dono/repo",
        _buscador(
            {"issues/comments": [{"id": 1, "body": "ok\n\n_Generated by [Claude Code](https://claude.ai/code)_"}]}
        ),
    )
    assert achados == 1


def test_github_varre_os_tres_lugares_que_o_cliente_le() -> None:
    """Comentário, corpo de issue/PR e comentário de revisão."""
    achados = va.verificar_github(
        "dono/repo",
        _buscador(
            {
                "issues/comments": [{"id": 1, "body": "🤖 Generated with Claude Code"}],
                "issues?state=all": [{"id": 2, "body": "Co-Authored-By: Claude <x@anthropic.com>"}],
                "pulls/comments": [{"id": 3, "body": "sugestão da Anthropic"}],
            }
        ),
    )
    assert achados == 3, "os três endpoints precisam ser varridos"


def test_github_nao_acusa_texto_limpo() -> None:
    achados = va.verificar_github(
        "dono/repo",
        _buscador(
            {
                "issues/comments": [{"id": 1, "body": "ver `.claude/skills/gcp-alupdata/SKILL.md`"}],
                "issues?state=all": [{"id": 2, "body": "CLAUDE.md só aponta para AGENTS.md"}],
            }
        ),
    )
    assert achados == 0


def test_github_tolera_corpo_nulo() -> None:
    """A API devolve body: null em issue sem descrição."""
    assert va.verificar_github("dono/repo", _buscador({"issues?state=all": [{"id": 1, "body": None}]})) == 0
